backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - label: "Blog en Español"
    name: "spanish_posts"
    folder: "_posts/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "lang", value: "es"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "lang", widget: "select", options: ["es", "eu"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Blog en Euskera"
    name: "basque_posts"
    folder: "_posts/eu"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "lang", value: "eu"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "lang", widget: "select", options: ["es", "eu"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Equipo en Español"
    name: "spanish_team"
    folder: "_team/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "lang", value: "es"}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Language", name: "lang", widget: "select", options: ["es", "eu"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Data"
    name: "data"
    files:
      - label: "Menú principal"
        name: "mainMenu"
        file: "_data/main-menu.yml"
        fields:
          - label: Items
            name: items
            widget: "list"
            fields:
              - {label: "Language", name: "lang", widget: "select", options: ["es", "eu"]}
              - label: Item
                name: item
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Url, name: url, widget: string}

      - label: "Contacto"
        name: "direcciones"
        file: "_data/contacto.yml"
        fields:
          - label: Dirección
            name: direccion
            widget: "object"
            fields:
              - {label: Name, name: name, widget: string}
              - label: Address
                name: address
                widget: object
                fields:
                  - {label: Calle, name: streetAddress, widget: string}
                  - {label: Localidad, name: addressLocality, widget: string}
                  - {label: Provincia, name: addressRegion, widget: string}
                  - {label: CP, name: postalCode, widget: string}
              - {label: Telephone, name: telephone, widget: string}
              - {label: Url, name: url, widget: string}
              - {label: Email, name: email, widget: string}
              - label: Horario
                name: openingHours
                widget: list
                default: []
              - label: Geo
                name: geo
                widget: object
                fields:
                  - {label: Latitude, name: latitude, widget: string}
                  - {label: Longitude, name: longitude, widget: string}

      - label: "Hero"
        name: "hero"
        file: "_data/hero.yml"
        fields:
          - {label: Image, name: image, widget: image}
          - label: Texto
            name: texto
            widget: list
            fields:
              - {label: "Language", name: "lang", widget: "select", options: ["es", "eu"]}
              - {label: "Link", name: link, widget: string}
              - {label: "Texto link", name: link-text, widget: string}
              - {label: "Body", name: "body", widget: "markdown"}
